#+title: Fork of Denote

This is a fork of Denote, developped by Protesilaos and many other
contributors (me included).

This fork is mostly compatible with Denote. There are a few differences
to be aware of. They are listed below.

The purpose of this fork is to provide a simplified version of the
original project focusing on the composability and hackability of
Denote. Those are core principles in both projects. The idea is to
provide a solid core of composable functions that users can use to build
their own personal note-taking system. As such, some convenience
functions provided in upstream are not provided by this fork. There are
many ways one can configure a note-taking system. The creation of the
personalized commands specific to a user's use cases are left to the
user. Examples on how to configure Denote to one's needs are given below
in this manual.

Functionality-wise, there should not be a lot missing from upstream.

Many new features are also developed here that I intend to contribute
back to Denote. The main ones are:

- ~denote-directory~ accepts a list of directories.
- File name components (title, keywords, signature, identifier) can be
  reordered (or absent)
- Improved renaming commands. ~denote-rename-file~ supports relocating a
  file and changing its file type. The code of the renaming commands has
  been simplified in the process.
- Variables to create custom denote commands (denote-forced-*
  variables).

I will be contributing what I can to Denote if it makes sense.

Like the code, part of this manual has been adapted from Protesilaos's
Denote manual.

* Contributions

Please contribute code and open issues in Denote if the feature is also
available there and makes sense in the main project.

I would also prefer that you open issues, rather than provide code. I
want to contribute back the code of this project to Denote and it
requires FSF copyright assignment for code contributions.

* COPYING

Copyright (C) 2022-2024  Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* Differences with the original project
** Removed code

I have removed a lot of code from Denote. Even if a lot of code has been
removed from Denote, most functionalities have been retained. The few
functionalities that have been removed were removed because users should
be responsible for their configuration or it is extra functionalities.

*** Removed: sluggification utility functions

I have disabled the default sluggification for keywords and
signature. Unlike titles, those components can be typed correctly from
the prompts by users. This functionality can be reinstated by user
through ~denote-file-name-slug-functions~.

Many internal functions that were involved in this task have been
removed.

*** Removed: The ~*-with-command~ commands

Reason for removal: Users should configure this themselves using more
specialized tools and to match their specific needs.

Alternatives: standard keymaps, transient keymaps, hydra, etc.

The reason for their suppression is that I want to emphasize the
composability of Denote while also simplifying the code base. I do not
want to cut on useful functionalities, but the job of selecting an
appropriate Emacs command is already handled well by various other
built-in mechanisms or external packages. They include: standard prefix
keymaps, transients, hydras, etc.

*** Removed: All convenience functions

Reason for removal: Users should create these functions according to
their specific needs and build a menu tailored to their needs (see
previous entry).

This includes ~denote-signature~, ~denote-date~, ~denote-type~,
~denote-link-with-signature~, etc.

Again, these provided useful functionalities, but they can easily be
defined again in a user's config according to one's particular needs for
his note-taking practices.

I think they may add confusion and hide the composability/hackability of
Denote. It is harder to feel confident that a custom function is the
right way to support one's need when there is already a function that
does something similar.

Some other functions like ~denote-link-with-signature~ are more
involved, but still simple enough to be part of a user's configuration
rather than in Denote.

*** Removed: Legacy .dir-locals.el mechanism with default-directory

Reason: This is legacy in Denote, removed here.

Previously, it was possible to set ~denote-directory~ to
=default-directory= (or =local=) in a =.dir-locals.el=. Denote has been
fixed and it does not mention this possibility anymore. I have removed
it here.

*** Removed: Aliases and obsolete names

Aliases and obsolete names have been removed.

*** Removed: ~denote-date-format~ variable

Reason for removal: What this variable does can controlled through the
user option ~denote-file-types~.

** New features
*** ~denote-directory~ accepts a list of directories

~denote-directory~ has gained the ability to receive a list of paths.
This means that it is now possible to have notes spread across various
locations. They do not need to be under a common directory.

Internally, the code has been adapted to work with a list of
directories. The function ~denote-directories~ returns the value of
~denote-directory~ as a list. The function ~denote-directory~ returns
the first element of ~denote-directory~ for backward compatability with
how it worked before.

New notes are created under the first element of ~denote-directory~. You
can still choose to be prompted for a directory if you want. See
~denote-prompts~.

*** Variables ~denote-forced-title~, ~denote-forced-keywords~, etc.

These variables are provided if a user wants to create a custom ~denote~
command that already has specific title, keywords, etc. We do not want
any prompting, just use the keyword specified.

Here is an example of the idea:

#+begin_src emacs-lisp
(defun my-denote-journal-command ()
  (let ((denote-forced-keywords '("journal"))
        (denote-forced-subdirectory "~/notes/journal/")
        (denote-prompts '(title)))
    (call-interactively #'denote)))
#+end_src

In this example, we have created a journaling command that always create
entries in the "journal/" subdirectory with the "journal" keyword and we
are prompted for a title.

*** Improved renaming-commands (many simplifications and convenience commands provided)

The two low-level functions ~denote--rename-file~ and
~denote--rename-get-file-info-from-prompts-or-existing~ are the only
necessary building blocks to handle all renaming commands.

With these, the code base is a lot cleaner. There is no duplicated code
anymore. All commands obey the variables ~denote-prompts~,
~denote-forced-*~ and ~denote-rename-no-confirm~ in the same way.

It is now also simple to implement your own renaming commands! Maybe you
would like a ~denote-rename-meta-data~ that only renames the keywords and
the signature (but not the title)? It is a trivial change away from
~denote-rename-keywords~.

Additionally, ~denote-rename-file~ (and all deriving from it) gains the
ability to change the file-type and the note's directory.

All other commands have been refactored as convenience commands that
use the 2 lower-level functions above as building blocks.

Here is the list of affected commands and their new status:

- ~denote-rename-file~: Refactored/simplified. This is still the main
  command, but its implementation is now trivial.

- ~denote-dired-rename-marked-files~: Refactored/simplified.

- ~denote-dired-rename-marked-files-with-keywords~: Refactored/simplified
  as a convenience.

- ~denote-rename-file-using-front-matter~: Provided as a convenience.
  However, its optional parameters have been dropped. They were not
  consistent with other commands anyway and it easy to create custom
  commands around this functionality.

- ~denote-dired-rename-marked-files-using-front-matter~:
  Refactored/simplified as a convenience.

- ~denote-keywords-{add/remove}~: Replaced with ~denote-rename-file-keywords~.

- ~denote-rename-{add/remove}-signature~: Replaced with
  ~denote-rename-file-signature~.

- ~denote-change-file-type~: Integrated into ~denote-rename-file~. A
  convenience command ~denote-rename-file-type~ is also provided.

*** ~denote-file-name-components~ controls the order and presence of the file name components

File name components (identifier, title, keywords and signature) can be
in any order.

Also, an item that is absent from this list will not be part of the file
name. It will only be in the front matter, if applicable.

Note that even though we allow identifiers to be absent from file names,
it is highly recommended to keep it. Otherwise, some functionalities may
not work as expected (renaming commands) or at all (link to such a
note).

TODO: Improve fontification

* Installation

This fork is only available as a git repository. You can clone it and
configure it in your =init.el=.

* Core of Denote and use cases
** What is a Denote note?

A Denote note is a single file with a specific file name
structure. Additionally, text files can have a front matter handled by
Denote.

Here is an example:

File name: =20240101T112314==z2a--my-note-example__emacs__philosophy.org=

Content:

#+begin_example
#title:     My note example   (raw title, ie not sluggified)
#keywords:    emacs philosophy   (same as file name)
#date:      2024-01-01
#+end_example

The file name contains an identifier, a signature, a title and keywords.
All components are optional.

Any file (pdf, video, image) can be converted to this file naming
scheme.

Text files can be of any extension if Denote is configured accordingly.

Denote can be seen as a package that helps organize simple text files by
giving them some structure. This structure is flexible and can be
adapted to one's needs. For example, Denote provides commands to add
keywords to files, a signature, rename a note, etc.

Additionally, Denote provide a linking mechanism between notes. It works
just like links in Org-mode.

While the above is the heart of Denote and could be considered
sufficient for a note-taking system, using Denote comes with other nice
features. In a Dired buffer, the components of your notes will stand
out, for instance. These extras facilities are explained later in this
manual.

** Core of Denote (creation, renaming and linking)

The core of Denote is its note creation, renaming and linking commands.

Creation/renaming:

- ~denote~

Renaming:
  
- ~denote-rename-file~

Linking:

- ~denote-link~

Link navigation commands:

- ~denote-find-link~
- ~denote-find-backlinks~
- ~denote-backlinks~

*** Other useful commands

Read their docstring.

File creation commands:

- ~denote-open-or-create~
- ~denote-region~
- ~denote-org-capture~

Note linking commands

- ~denote-link-or-create~
- ~denote-link-after-creating~
- ~denote-add-links~
- ~denote-link-dired-marked-notes~

Renaming functions:

- ~denote-dired-rename-files~
- ~denote-dired-rename-marked-files-with-keywords~
- ~denote-rename-file-using-front-matter~
- ~denote-dired-rename-marked-files-using-front-matter~

*** Building blocks for custom commands

~denote~, ~denote-link~ and ~denote-rename-file~ commands are already usable
as building blocks to create custom commands specialized for one's use
cases. Explanations and examples are provided in the next section.

*** Configuration options

Options to build custom commands:

- ~denote-prompts~
- ~denote-directories~
- ~denote-link-description-function~
- ~denote-file-type~

General configuration options:

- ~denote-file-types~
- ~denote-file-name-slug-functions~
- ~denote-templates~
- ~denote-excluded-directories-regexp~
- ~denote-after-new-note-hook~
- ~denote-rename-file-hook~

Other options:

- ~denote-save-buffers~
- ~denote-sort-keywords~
- ~denote-date-prompt-use-org-read-date~
- ~denote-backlinks-show-context~
- ~denote-rename-confirmations~
- ~denote-infer-keywords~
- ~denote-excluded-keywords-regexp~

** Configuring Denote for specific use cases

While Denote comes with sensible defaults, it can be configured to
handle one's specific use cases.

Following Denote's philosophy, various commands can be created specific
to one's needs. Here is the general template for such a command

#+begin_src emacs-lisp
(defun my-denote-link ()
  (interactive)
  (let ((denote-prompts '(title signature))
        (denote-file-type 'md-yaml)
        (denote-link-description-function (lambda () "Link")))
    (call-interactively #'denote-link-or-create)))
#+end_src

When a user calls this custom command, the ~denote-link-or-create~
function is called and doing all the work. The link descriptions will
always be "Link". If the linked file does not exist, a new
note (of type md-yaml) will be created.

*** Main example and sample configuration

This is a general example highlighting the power of Denote and how it
can be configured to meet one's requirements for note-taking.

#+begin_src emacs-lisp
(setq denote-directory '("~/notes" "~/music"))
(setq denote-prompts '(title keywords signature))

(defun denote-file-type ()
  (interactive)
  (let ((denote-prompts '(title keywords file-type)))
    (call-interactively #'denote)))

(defun denote-file-signature ()
  (interactive)
  (let ((denote-prompts '(title keywords signature)))
    (call-interactively #'denote)))

(defun denote-in-work-silo ()
  (interactive)
  (let ((denote-directory '("~/work/"))
        (denote-prompts '(title keywords file-type)))
    (call-interactively #'denote)))

(defun denote-signature-in-work-silo ()
  (interactive)
  (let ((denote-directory '("~/work/"))
        (denote-prompts '(title keywords signature)))
    (call-interactively #'denote)))

(defun my-journal-command ()
  (interactive)
  (let ((denote-prompts '(title))
        (denote-forced-keywords '("journal"))
        (denote-forced-directory '()))
    (call-interactively #'denote)))

(let ((map global-map))
  ;; Creation commands
  (define-key map (kbd "C-c n n") #'denote)
  (define-key map (kbd "C-c n t") #'denote-file-type)
  (define-key map (kbd "C-c n s") #'denote-signature)
  (define-key map (kbd "C-c w n") #'denote-in-work-silo)
  (define-key map (kbd "C-c w s") #'denote-signature-in-work-silo)
  (define-key map (kbd "C-c n j") #'my-journal-command)

  ;; Other commands
  (define-key map (kbd "C-c n i") #'denote-link)
  (define-key map (kbd "C-c n b") #'denote-backlinks)
  (define-key map (kbd "C-c n f f") #'denote-find-link)
  (define-key map (kbd "C-c n f b") #'denote-find-backlink)
  (define-key map (kbd "C-c n r") #'denote-rename-file))
#+end_src

*** Use case: Two silos (home and work) and .dir-locals.el

~denote-directory~ can be set in a .dir-locals.el file.

*** Use case: A directory of notes inside a project (using .dir-locals.el)

Let's say you have a project directory. Under that directory, you want
to have ssubdirectory containing notes. Anywhere in your project, you
want to have access to be able to create notes in that subdirectory.

The solution is simple. You can have a =.dir-locals.el= file at the root
of your project and with this content:

#+begin_src emacs-lisp
((nil . ((denote-directory . ("~/path/to/project/notes/")))))
#+end_src

*** Use case: Always prompt for title, signature and file-type (in that order)

#+begin_src emacs-lisp
(setq denote-prompts '(title signature file-type))
#+end_src

*** Use case: Prompt for title, but fix the subdirectory to "journal/" and the keywords to '("journal")

#+begin_src emacs-lisp
(defun my-custom-command ()
  (interactive)
  (let ((denote-prompts '(title))
        (denote-forced-keywords '("journal"))
        (denote-forced-directory '()))
    (call-interactively #'denote)))
#+end_src

It is even possible to fix the title to display today's information. See
the next example.

*** Use case: Maintain a journal

This command does not prompt and creates a note titled
"20240330T111111--saturday-30-march-2024__journal.txt" in the "journal/"
subdirectory. If a note for that date already exists, open it instead.

#+begin_src emacs-lisp
(defun my-journal-command ()
  (interactive)
  (let ((existing-entry (car (denote-directories-files
                               (concat (format-time-string "%Y%m%d" (current-time)) "T[0-9]\\{6\\}.*__journal")))
        (denote-prompts '())
        (denote-file-type 'text)
        (denote-forced-title (format-time-string "%A %-d %B %Y" (current-time)))
        (denote-forced-keywords '("journal"))
        (denote-forced-directory "path/to/notes/journal/"))
    (if existing-entry
        (find-file existing-entry)
      (call-interactively #'denote)))))
#+end_src

*** Use case: Organize a menu of Denote custom commands

You can use standard keymaps, transient or external packages (for
example Hydra) to create a menu of custom commands.

*** Use case: Custom link description

The descriptions of links can be configured with
~denote-link-description-function~.

Links can be made to look like:
- "Link"
- "20240101T111111--My-note.org"
- "My file title"
- "My file title (keyword1, keyword2)"
- "sig1z3   My other title"  (the default if signature is present)
- "My other title (sig1z3)"
- A prompt for the description
- etc.

*** Use case: Pre-fill the content of your notes with a template

Check ~denote-templates~.

*** Use case: Composing everything together

See the main example above.

*** Use case: Customize the front matter

The front matter can be customized through the variable
~denote-file-types~.

Lines can be removed and reordered.

*** Use case: Add a new file type

Denote comes with 4 supported files types (org, md-yaml, md-toml and
txt), but other formats may be supported. They must be configured with
~denote-file-types~.

*** Use case: Apply a function on file name components (sluggification)

By default, when a new note is created, the title that is typed is
"sluggified". Spaces are converted to hyphens and special characters are
removed. The original title is preserved in the front matter of the
file.

This sluggification can be configured with
~denote-file-name-slug-functions~ for each component (title, keyword,
signature).

* Acknowledgements
:PROPERTIES:
:CUSTOM_ID: h:f8126820-3b59-49fa-bcc2-73bd60132bb9
:END:
#+cindex: Contributors

Denote is meant to be a collective effort.  Every bit of help matters.

+ Author/maintainer of Denote :: Protesilaos Stavrou.

+ Contributions to code or the manual :: Abin Simon, Adam Růžička,
  Alan Schmitt, Ashton Wiersdorf, Benjamin Kästner, Bruno Boal,
  Charanjit Singh, Clemens Radermacher, Colin McLear, Damien Cassou,
  Eduardo Grajeda, Elias Storms, Eshel Yaron, Florian, Glenna D.,
  Graham Marlow, Hilde Rhyne, Ivan Sokolov, Jack Baty, Jean-Charles
  Bagneris, Jean-Philippe Gagné Guay, Joseph Turner, Jürgen Hötzel,
  Kaushal Modi, Kai von Fintel, Kostas Andreadis, Kyle Meyer, Marc
  Fargas, Matthew Lemon, Noboru Ota (nobiot), Norwid Behrnd, Peter
  Prevos, Philip Kaludercic, Quiliro Ordóñez, Stefan Monnier, Stefan
  Thesing, Thibaut Benjamin, Tomasz Hołubowicz, Vedang Manerikar,
  Wesley Harvey, ezchi, leinfink (Henrik), mentalisttraceur,
  relict007.

+ Ideas and/or user feedback :: Abin Simon, Aditya Yadav, Alan
  Schmitt, Aleksandr Vityazev, Alfredo Borrás, Ashton Wiersdorf,
  Benjamin Kästner, Claudiu Tănăselia, Colin McLear, Damien Cassou,
  Elias Storms, Federico Stilman, Florian, Frédéric Willem Frank
  Ehmsen, Glenna D., Guo Yong, Hanspeter Gisler, Jack Baty, Jay
  Rajput, Jean-Charles Bagneris, Jens Östlund, Jeremy Friesen,
  Jonathan Sahar, Johan Bolmsjö, Jousimies, Juanjo Presa, Kai von
  Fintel, Kaushal Modi, M. Hadi Timachi, Mark Olson, Mirko Hernandez,
  Niall Dooley, Paul van Gelder, Peter Prevos, Peter Smith, Suhail
  Singh, Shreyas Ragavan, Stefan Thesing, Summer Emacs, Sven Seebeck,
  Taoufik, TJ Stankus, Viktor Haag, Wade Mealing, Yi Liu, Ypot,
  atanasj, babusri, doolio, drcxd, hpgisler, pRot0ta1p, rbenit68,
  relict007, sienic, sundar bp.

Special thanks to Peter Povinec who helped refine the file-naming
scheme, which is the cornerstone of this project.

Special thanks to Jean-Philippe Gagné Guay for the numerous
contributions to the code base.

* GNU Free Documentation License
:PROPERTIES:
:APPENDIX: t
:CUSTOM_ID: h:2d84e73e-c143-43b5-b388-a6765da974ea
:END:

#+texinfo: @include doclicense.texi

#+begin_export html
<pre>

                GNU Free Documentation License
                 Version 1.3, 3 November 2008


 Copyright (C) 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
     <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other
functional and useful document "free" in the sense of freedom: to
assure everyone the effective freedom to copy and redistribute it,
with or without modifying it, either commercially or noncommercially.
Secondarily, this License preserves for the author and publisher a way
to get credit for their work, while not being considered responsible
for modifications made by others.

This License is a kind of "copyleft", which means that derivative
works of the document must themselves be free in the same sense.  It
complements the GNU General Public License, which is a copyleft
license designed for free software.

We have designed this License in order to use it for manuals for free
software, because free software needs free documentation: a free
program should come with manuals providing the same freedoms that the
software does.  But this License is not limited to software manuals;
it can be used for any textual work, regardless of subject matter or
whether it is published as a printed book.  We recommend this License
principally for works whose purpose is instruction or reference.


1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that
contains a notice placed by the copyright holder saying it can be
distributed under the terms of this License.  Such a notice grants a
world-wide, royalty-free license, unlimited in duration, to use that
work under the conditions stated herein.  The "Document", below,
refers to any such manual or work.  Any member of the public is a
licensee, and is addressed as "you".  You accept the license if you
copy, modify or distribute the work in a way requiring permission
under copyright law.

A "Modified Version" of the Document means any work containing the
Document or a portion of it, either copied verbatim, or with
modifications and/or translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of
the Document that deals exclusively with the relationship of the
publishers or authors of the Document to the Document's overall
subject (or to related matters) and contains nothing that could fall
directly within that overall subject.  (Thus, if the Document is in
part a textbook of mathematics, a Secondary Section may not explain
any mathematics.)  The relationship could be a matter of historical
connection with the subject or with related matters, or of legal,
commercial, philosophical, ethical or political position regarding
them.

The "Invariant Sections" are certain Secondary Sections whose titles
are designated, as being those of Invariant Sections, in the notice
that says that the Document is released under this License.  If a
section does not fit the above definition of Secondary then it is not
allowed to be designated as Invariant.  The Document may contain zero
Invariant Sections.  If the Document does not identify any Invariant
Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed,
as Front-Cover Texts or Back-Cover Texts, in the notice that says that
the Document is released under this License.  A Front-Cover Text may
be at most 5 words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy,
represented in a format whose specification is available to the
general public, that is suitable for revising the document
straightforwardly with generic text editors or (for images composed of
pixels) generic paint programs or (for drawings) some widely available
drawing editor, and that is suitable for input to text formatters or
for automatic translation to a variety of formats suitable for input
to text formatters.  A copy made in an otherwise Transparent file
format whose markup, or absence of markup, has been arranged to thwart
or discourage subsequent modification by readers is not Transparent.
An image format is not Transparent if used for any substantial amount
of text.  A copy that is not "Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain
ASCII without markup, Texinfo input format, LaTeX input format, SGML
or XML using a publicly available DTD, and standard-conforming simple
HTML, PostScript or PDF designed for human modification.  Examples of
transparent image formats include PNG, XCF and JPG.  Opaque formats
include proprietary formats that can be read and edited only by
proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the
machine-generated HTML, PostScript or PDF produced by some word
processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself,
plus such following pages as are needed to hold, legibly, the material
this License requires to appear in the title page.  For works in
formats which do not have any title page as such, "Title Page" means
the text near the most prominent appearance of the work's title,
preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of
the Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose
title either is precisely XYZ or contains XYZ in parentheses following
text that translates XYZ in another language.  (Here XYZ stands for a
specific section name mentioned below, such as "Acknowledgements",
"Dedications", "Endorsements", or "History".)  To "Preserve the Title"
of such a section when you modify the Document means that it remains a
section "Entitled XYZ" according to this definition.

The Document may include Warranty Disclaimers next to the notice which
states that this License applies to the Document.  These Warranty
Disclaimers are considered to be included by reference in this
License, but only as regards disclaiming warranties: any other
implication that these Warranty Disclaimers may have is void and has
no effect on the meaning of this License.

2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either
commercially or noncommercially, provided that this License, the
copyright notices, and the license notice saying this License applies
to the Document are reproduced in all copies, and that you add no
other conditions whatsoever to those of this License.  You may not use
technical measures to obstruct or control the reading or further
copying of the copies you make or distribute.  However, you may accept
compensation in exchange for copies.  If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and
you may publicly display copies.


3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have
printed covers) of the Document, numbering more than 100, and the
Document's license notice requires Cover Texts, you must enclose the
copies in covers that carry, clearly and legibly, all these Cover
Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
the back cover.  Both covers must also clearly and legibly identify
you as the publisher of these copies.  The front cover must present
the full title with all words of the title equally prominent and
visible.  You may add other material on the covers in addition.
Copying with changes limited to the covers, as long as they preserve
the title of the Document and satisfy these conditions, can be treated
as verbatim copying in other respects.

If the required texts for either cover are too voluminous to fit
legibly, you should put the first ones listed (as many as fit
reasonably) on the actual cover, and continue the rest onto adjacent
pages.

If you publish or distribute Opaque copies of the Document numbering
more than 100, you must either include a machine-readable Transparent
copy along with each Opaque copy, or state in or with each Opaque copy
a computer-network location from which the general network-using
public has access to download using public-standard network protocols
a complete Transparent copy of the Document, free of added material.
If you use the latter option, you must take reasonably prudent steps,
when you begin distribution of Opaque copies in quantity, to ensure
that this Transparent copy will remain thus accessible at the stated
location until at least one year after the last time you distribute an
Opaque copy (directly or through your agents or retailers) of that
edition to the public.

It is requested, but not required, that you contact the authors of the
Document well before redistributing any large number of copies, to
give them a chance to provide you with an updated version of the
Document.


4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under
the conditions of sections 2 and 3 above, provided that you release
the Modified Version under precisely this License, with the Modified
Version filling the role of the Document, thus licensing distribution
and modification of the Modified Version to whoever possesses a copy
of it.  In addition, you must do these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct
   from that of the Document, and from those of previous versions
   (which should, if there were any, be listed in the History section
   of the Document).  You may use the same title as a previous version
   if the original publisher of that version gives permission.
B. List on the Title Page, as authors, one or more persons or entities
   responsible for authorship of the modifications in the Modified
   Version, together with at least five of the principal authors of the
   Document (all of its principal authors, if it has fewer than five),
   unless they release you from this requirement.
C. State on the Title page the name of the publisher of the
   Modified Version, as the publisher.
D. Preserve all the copyright notices of the Document.
E. Add an appropriate copyright notice for your modifications
   adjacent to the other copyright notices.
F. Include, immediately after the copyright notices, a license notice
   giving the public permission to use the Modified Version under the
   terms of this License, in the form shown in the Addendum below.
G. Preserve in that license notice the full lists of Invariant Sections
   and required Cover Texts given in the Document's license notice.
H. Include an unaltered copy of this License.
I. Preserve the section Entitled "History", Preserve its Title, and add
   to it an item stating at least the title, year, new authors, and
   publisher of the Modified Version as given on the Title Page.  If
   there is no section Entitled "History" in the Document, create one
   stating the title, year, authors, and publisher of the Document as
   given on its Title Page, then add an item describing the Modified
   Version as stated in the previous sentence.
J. Preserve the network location, if any, given in the Document for
   public access to a Transparent copy of the Document, and likewise
   the network locations given in the Document for previous versions
   it was based on.  These may be placed in the "History" section.
   You may omit a network location for a work that was published at
   least four years before the Document itself, or if the original
   publisher of the version it refers to gives permission.
K. For any section Entitled "Acknowledgements" or "Dedications",
   Preserve the Title of the section, and preserve in the section all
   the substance and tone of each of the contributor acknowledgements
   and/or dedications given therein.
L. Preserve all the Invariant Sections of the Document,
   unaltered in their text and in their titles.  Section numbers
   or the equivalent are not considered part of the section titles.
M. Delete any section Entitled "Endorsements".  Such a section
   may not be included in the Modified Version.
N. Do not retitle any existing section to be Entitled "Endorsements"
   or to conflict in title with any Invariant Section.
O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or
appendices that qualify as Secondary Sections and contain no material
copied from the Document, you may at your option designate some or all
of these sections as invariant.  To do this, add their titles to the
list of Invariant Sections in the Modified Version's license notice.
These titles must be distinct from any other section titles.

You may add a section Entitled "Endorsements", provided it contains
nothing but endorsements of your Modified Version by various
parties--for example, statements of peer review or that the text has
been approved by an organization as the authoritative definition of a
standard.

You may add a passage of up to five words as a Front-Cover Text, and a
passage of up to 25 words as a Back-Cover Text, to the end of the list
of Cover Texts in the Modified Version.  Only one passage of
Front-Cover Text and one of Back-Cover Text may be added by (or
through arrangements made by) any one entity.  If the Document already
includes a cover text for the same cover, previously added by you or
by arrangement made by the same entity you are acting on behalf of,
you may not add another; but you may replace the old one, on explicit
permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License
give permission to use their names for publicity for or to assert or
imply endorsement of any Modified Version.


5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this
License, under the terms defined in section 4 above for modified
versions, provided that you include in the combination all of the
Invariant Sections of all of the original documents, unmodified, and
list them all as Invariant Sections of your combined work in its
license notice, and that you preserve all their Warranty Disclaimers.

The combined work need only contain one copy of this License, and
multiple identical Invariant Sections may be replaced with a single
copy.  If there are multiple Invariant Sections with the same name but
different contents, make the title of each such section unique by
adding at the end of it, in parentheses, the name of the original
author or publisher of that section if known, or else a unique number.
Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History"
in the various original documents, forming one section Entitled
"History"; likewise combine any sections Entitled "Acknowledgements",
and any sections Entitled "Dedications".  You must delete all sections
Entitled "Endorsements".


6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other
documents released under this License, and replace the individual
copies of this License in the various documents with a single copy
that is included in the collection, provided that you follow the rules
of this License for verbatim copying of each of the documents in all
other respects.

You may extract a single document from such a collection, and
distribute it individually under this License, provided you insert a
copy of this License into the extracted document, and follow this
License in all other respects regarding verbatim copying of that
document.


7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate
and independent documents or works, in or on a volume of a storage or
distribution medium, is called an "aggregate" if the copyright
resulting from the compilation is not used to limit the legal rights
of the compilation's users beyond what the individual works permit.
When the Document is included in an aggregate, this License does not
apply to the other works in the aggregate which are not themselves
derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these
copies of the Document, then if the Document is less than one half of
the entire aggregate, the Document's Cover Texts may be placed on
covers that bracket the Document within the aggregate, or the
electronic equivalent of covers if the Document is in electronic form.
Otherwise they must appear on printed covers that bracket the whole
aggregate.


8. TRANSLATION

Translation is considered a kind of modification, so you may
distribute translations of the Document under the terms of section 4.
Replacing Invariant Sections with translations requires special
permission from their copyright holders, but you may include
translations of some or all Invariant Sections in addition to the
original versions of these Invariant Sections.  You may include a
translation of this License, and all the license notices in the
Document, and any Warranty Disclaimers, provided that you also include
the original English version of this License and the original versions
of those notices and disclaimers.  In case of a disagreement between
the translation and the original version of this License or a notice
or disclaimer, the original version will prevail.

If a section in the Document is Entitled "Acknowledgements",
"Dedications", or "History", the requirement (section 4) to Preserve
its Title (section 1) will typically require changing the actual
title.


9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document
except as expressly provided under this License.  Any attempt
otherwise to copy, modify, sublicense, or distribute it is void, and
will automatically terminate your rights under this License.

However, if you cease all violation of this License, then your license
from a particular copyright holder is reinstated (a) provisionally,
unless and until the copyright holder explicitly and finally
terminates your license, and (b) permanently, if the copyright holder
fails to notify you of the violation by some reasonable means prior to
60 days after the cessation.

Moreover, your license from a particular copyright holder is
reinstated permanently if the copyright holder notifies you of the
violation by some reasonable means, this is the first time you have
received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

Termination of your rights under this section does not terminate the
licenses of parties who have received copies or rights from you under
this License.  If your rights have been terminated and not permanently
reinstated, receipt of a copy of some or all of the same material does
not give you any rights to use it.


10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the
GNU Free Documentation License from time to time.  Such new versions
will be similar in spirit to the present version, but may differ in
detail to address new problems or concerns.  See
https://www.gnu.org/licenses/.

Each version of the License is given a distinguishing version number.
If the Document specifies that a particular numbered version of this
License "or any later version" applies to it, you have the option of
following the terms and conditions either of that specified version or
of any later version that has been published (not as a draft) by the
Free Software Foundation.  If the Document does not specify a version
number of this License, you may choose any version ever published (not
as a draft) by the Free Software Foundation.  If the Document
specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a
version permanently authorizes you to choose that version for the
Document.

11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any
World Wide Web server that publishes copyrightable works and also
provides prominent facilities for anybody to edit those works.  A
public wiki that anybody can edit is an example of such a server.  A
"Massive Multiauthor Collaboration" (or "MMC") contained in the site
means any set of copyrightable works thus published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0
license published by Creative Commons Corporation, a not-for-profit
corporation with a principal place of business in San Francisco,
California, as well as future copyleft versions of that license
published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in
part, as part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this
License, and if all works that were first published under this License
somewhere other than this MMC, and subsequently incorporated in whole or
in part into the MMC, (1) had no cover texts or invariant sections, and
(2) were thus incorporated prior to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site
under CC-BY-SA on the same site at any time before August 1, 2009,
provided the MMC is eligible for relicensing.


ADDENDUM: How to use this License for your documents

To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and
license notices just after the title page:

    Copyright (c)  YEAR  YOUR NAME.
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in the section entitled "GNU
    Free Documentation License".

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the "with...Texts." line with this:

    with the Invariant Sections being LIST THEIR TITLES, with the
    Front-Cover Texts being LIST, and with the Back-Cover Texts being LIST.

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of
free software license, such as the GNU General Public License,
to permit their use in free software.
</pre>
#+end_export

#+html: <!--



